# Data Configuration
data:
  # ETF Universe
  etfs:
    sectors:
      - XLF  # Financial
      - XLC  # Communication Services
      - XLY  # Consumer Discretionary
      - XLP  # Consumer Staples
      - XLE  # Energy
      - XLV  # Healthcare
      - XLI  # Industrial
      - XLB  # Materials
      - XLRE # Real Estate
      - XLK  # Technology
      - XLU  # Utilities
    benchmark: SPY  # S&P 500
    
  # Date Range
  date_range:
    start: "2018-01-01"
    end: null  # Use null for current date
    
  # Data Sources
  sources:
    market_data:
      provider: yfinance
      interval: 1d
      auto_adjust: true
      prepost: false
      
    economic_data:
      provider: fred
      api_key: ${FRED_API_KEY}  # Set in environment
      indicators:
        # Interest Rates
        - DGS10    # 10-Year Treasury
        - DGS2     # 2-Year Treasury
        - DFF      # Federal Funds Rate
        - SOFR     # SOFR Rate
        
        # Economic Indicators
        - GDP      # GDP
        - UNRATE   # Unemployment Rate
        - CPIAUCSL # CPI
        - INDPRO   # Industrial Production
        
        # Financial Conditions
        - DEXUSEU  # USD/EUR Exchange Rate
        - DCOILWTICO # WTI Oil Price
        - GOLDAMGBD228NLBM # Gold Price
        - NFCI     # Financial Conditions Index
        
    alternative_data:
      news_sentiment:
        provider: newsapi
        api_key: ${NEWS_API_KEY}
        
      social_sentiment:
        provider: twitter
        api_key: ${TWITTER_API_KEY}

# Feature Engineering
features:
  # Technical Indicators
  technical:
    # Momentum
    - rsi:
        period: 14
    - macd:
        fast: 12
        slow: 26
        signal: 9
    - stochastic:
        period: 14
        
    # Volatility
    - bollinger_bands:
        period: 20
        std_dev: 2
    - atr:
        period: 14
    - historical_volatility:
        period: 20
        
    # Volume
    - obv: {}
    - mfi:
        period: 14
    - vwap: {}
    
    # Trend
    - ema:
        periods: [10, 20, 50, 200]
    - adx:
        period: 14
        
  # Fundamental Factors
  fundamental:
    # Valuation
    - pe_ratio: {}
    - pb_ratio: {}
    - dividend_yield: {}
    
    # Growth
    - earnings_growth: {}
    - revenue_growth: {}
    
  # Engineered Features
  engineered:
    # Time-based
    - returns:
        periods: [1, 5, 10, 20, 60]
    - log_returns:
        periods: [1, 5, 10, 20]
        
    # Statistical
    - rolling_mean:
        windows: [5, 10, 20, 60]
    - rolling_std:
        windows: [5, 10, 20, 60]
    - rolling_skew:
        window: 20
    - rolling_kurt:
        window: 20
        
    # Frequency Domain
    - fft_components:
        n_components: 3
    - wavelet_coefficients:
        wavelet: db4
        level: 3
        
    # Cross-sectional
    - relative_strength:
        universe: sectors
    - correlation_features:
        window: 60
        
  # Window Configuration
  window:
    sequence_length: 60  # LSTM input window
    prediction_horizon: 5
    step_size: 1  # Sliding window step

# Data Processing
processing:
  # Missing Data
  missing_data:
    method: forward_fill
    max_consecutive_fill: 5
    
  # Outliers
  outliers:
    method: winsorize
    limits: [0.01, 0.99]
    
  # Scaling
  scaling:
    method: standard  # Options: standard, minmax, robust
    feature_range: [-1, 1]  # For minmax
    
  # Data Quality
  quality_checks:
    check_missing: true
    check_outliers: true
    check_stationarity: true
    min_data_points: 252  # 1 year of trading days

# Storage Configuration
storage:
  # Cache
  cache:
    enabled: true
    backend: redis
    ttl: 3600  # seconds
    
  # Database
  database:
    type: timescaledb
    connection_string: ${DATABASE_URL}
    
  # File Storage
  file_storage:
    raw_data: ./data/raw
    processed_data: ./data/processed
    features: ./data/features
    
# Data Pipeline
pipeline:
  # Parallel Processing
  parallel:
    enabled: true
    n_jobs: -1  # Use all cores
    
  # Batch Processing
  batch:
    size: 1000
    prefetch: 2
    
  # Streaming
  streaming:
    enabled: false
    buffer_size: 100